# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/basic"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/css-modules/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/default-layout/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/esbuild-settings"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/markdown-settings/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/nested-dest/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/preact-isomorphic/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/react/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/string-layouts/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/tailwind/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/type-stripping/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/uhtml-isomorphic/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/examples/worker-examples/"
    schedule:
      interval: "daily"
  # Enable version updates for pnpm
  # Enable updates to github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
